---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.22.0.4163-d8c4875dd
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
      - 44
      - 109
    service:
      enabled: true
      type: LoadBalancer
      externalIPs:
      - 192.168.69.140
      externalTrafficPolicy: Local
      port:
        port: 32400
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - host: plex.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "plex.devbu.io"
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      transcode:
        enabled: false
        emptyDir:
          medium: "Memory"
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
      readOnly: true
    - name: media-serenity
      mountPath: "/media-serenity"
      readOnly: true
    - name: cert
      mountPath: "/cert"
      readOnly: true
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    - name: media-serenity
      persistentVolumeClaim:
        claimName: nfs-media-serenity-pvc
    - name: cert
      secret:
        secretName: devbu-io-tls
        items:
        - key: keystore.p12
          path: devbu-io-tls.p12
    podAnnotations:
      backup.velero.io/backup-volumes: config
      secret.reloader.stakater.com/reload: "devbu-io-tls"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k8s-worker-d
              - k8s-worker-e
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 12000Mi
