---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-serenity-pv
spec:
  storageClassName: media-serenity
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.42.50
    path: /volume1/Media
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-serenity-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-serenity
  resources:
    requests:
      storage: 1Mi
