---

- hosts:
  - worker-nodes
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
  - name: Pausing for 5 seconds...
    pause:
      seconds: 5
  tasks:
  - name: remove /var/lib/rook
    become: true
    ansible.builtin.file:
      state: absent
      path: "/var/lib/rook"
    when:
    - rook_ceph.enabled is defined
    - rook_ceph.enabled
  - name: zap the drives
    become: true
    ansible.builtin.shell: >
      sgdisk --zap-all {{ item }} || true
    loop:
    - "{{ rook_ceph.devices }}"
    when:
    - rook_ceph.enabled is defined
    - rook_ceph.enabled
  - name: remove lvm partitions
    become: true
    ansible.builtin.shell: "{{ item }}"
    loop:
    - ls /dev/mapper/ceph--* | xargs -I% -- fuser --kill %
    - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup clear %
    - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup remove -f %
    - ls /dev/mapper/ceph--* | xargs -I% -- rm -rf %
    when:
    - rook_ceph.enabled is defined
    - rook_ceph.enabled
  - name: wipe the block device
    become: true
    ansible.builtin.command: "wipefs -af {{ item }}"
    with_items:
    - "{{ rook_ceph.devices }}"
    when:
    - rook_ceph.enabled is defined
    - rook_ceph.enabled
