---

#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration
#

# Define the host as a control plane node
k3s_control_node: false

# k3s settings for all worker nodes
# ...see https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration
k3s_agent:
  node-external-ip: "{{ ansible_host }}"
  node-ip: "{{ digitalocean_private_ip }}"
  # Apply Labels
  node-label:
  - "node-role.kubernetes.io/worker=true"
