---

# Enable to skip apt upgrade
# skip_upgrade_packages: true
# Enable to skip removing crufty packages
# skip_remove_packages: true

# Timezone for the servers
timezone: "America/New_York"

# Set custom ntp servers
# ntp_servers:
#   primary:
#   - "time.cloudflare.com"
#   - "time.google.com"
#   fallback:
#   - "0.us.pool.ntp.org"
#   - "1.us.pool.ntp.org"
#   - "2.us.pool.ntp.org"
#   - "3.us.pool.ntp.org"

# Additional ssh public keys to add to the nodes
ssh_authorized_keys:
# MacBook
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDO1R1i7dP0dY3f3rnlIQjVPsg3p0Xvz/16oZq+cUmE+O3An9qKQNUwWA98EdnMfq09qLpU1OBSafrLjZ8rd4+4KZJNhFgOCX1qq9GDo+o87toYZUvZ6ftdokpgYlYh0sSUxCjbEnaYAr9W2ZYs32fSJAZdoSydUp9gsTlYQJtq4OYKeQd4gd0oJ2F+L3Rv/HwY1U2+ynW4XnsnbfYky9DkQJIgirFwhwsuDot7VMW14mvI1T4IN+rGHfvHsEqsKrVCOUwfsgnNEXR4R5lSE0mNgZiEFnh/F7pA8QGmcKrNv/Fd4cZRdWxtDdrmEVVtbVnlnRrtV0NS9VqJiJm6Rm9QQ9LLemHAGJHT90hUknSB5qw1pxJ/uZ5hCQzOAzfABQ+Jgj4VzT4PpwaGF529v9VSsV6KPPyF0pP8YNKgRaSBxFqFTwIBLH9eBiE0neIHDGBBi3H9pbYtlMHoy9pnepSPPhD4vSiVbFVSFxwKJ9hoVpRKt3gZuhtIMuDVFpgiAHYE9VYSKbfH0FuBLqrNzF0inkn0Luo+wWyCUNO2y+mZZKpm61huCgdWGL4HfSNLKqwxBtG0oKI1GISGzipay9m0u0JrPjeNr0bD0Sg28aDhjEeds6P9Xe/j/QZg6YWW11rUH33GFljHo6Llu9rBfoiM9BJqXDyInkzfYcq91cojmw== devin.kray@gmail.com"
# Phone / Devin / Termux
- "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB75L4ZEN17wcsK765dWzqlf0lY+sbK25QCIvebB/+1x devin.kray@gmail.com"
# PC / Study / WSL2
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPmH8sRgmWWX5sUA2yrfvZMV3jZPSNEsRLYpQbRFTVwkgFMFibqgzaCkaYmmkx8iwGJCAv+hQpEsdnV90vn2RNBGjeEX6GScr8XYhcapiEx3hcIdjxZskJVllsSwnrgd21QpUPI9Y9CIRYgYGeTwuyhnYl2DvWDCXPOU7HiCoW5mdUuQkl+soio4v8C1aroD5je1Q0usMDFBQ2N+frKGzZseR5zBhWwjRG599Z4JgQWIF1LPc4jPfs24vaMy2kMUW5jDIpQjiE1O+xEfNb7k6qyIVcH6GGEv1AileBHj+IXE8KzyxtoIh88Re2mvVuFIVOsResHf0zP5jJqoOdPmnVmzo+sohD/7T+rhbRCDMEGB6eKTqUR9JWKNj/EEgbsYkzYs8XTZqLhn+4QI6EHa9+G/cautts+NOfSHakSMZ09/bn2xf5UFjdqWKLqS7FQ5qAe20iQibn95YOBgLAKxk5gTfBN0sRXuDovvvuzgE7YYyqeN+rgISWSNN3uIyjISKBCZmImfPp+lnG6ucJj7Uj22+1ark5bYvrOqgzCmhVO+JARCNABPx2I4BGTF0WEDN0hmSeTDsBbhrWLmLl/TqoxSojSTYaAhzXQAYsvcp/mu3MSkIW8S8uKkJWMEXWfQQt3gepK+83nuhh8EMrjXw5RVsHyGwyK9BE+pIhdviC0w== devin.kray@gmail.com"
# PC / Basement / Linux
- "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiddUjKM30+14w410mfhEpQ4N9CQ9+AdPK3qwXxMw70 devin.kray@gmail.com"
