---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rtorrent-flood
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: rtorrent-flood
      version: 6.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
    - name: update-perms
      image: busybox
      command: ["sh", "-c", "chown -R 568:568 /config"]
      volumeMounts:
      - name: config
        mountPath: /config
      securityContext:
        runAsUser: 0
    image:
      repository: jesec/rtorrent-flood
      tag: latest@sha256:5ff0125ea0e2befbc2ba2f2143e130819db645cb5ef68b44a0712b8162a16f47
    env:
      TZ: "America/New_York"
      HOME: "/config"
    args:
    - "flood"
    - "--host 0.0.0.0"
    - "--rtorrent"
    - "--port 3000"
    - "--allowedpath /media-rocinante/Downloads/rtorrent-flood"
    config: |
      session.use_lock.set = no
      method.insert = cfg.basedir,  private|const|string, (cat,(fs.homedir),"/.local/share/rtorrent/")
      method.insert = cfg.download, private|const|string, (cat,"/media-rocinante/Downloads/rtorrent-flood/","completed/")
      method.insert = cfg.logs,     private|const|string, (cat,"/media-rocinante/Downloads/rtorrent-flood/","log/")
      method.insert = cfg.logfile,  private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
      method.insert = cfg.session,  private|const|string, (cat,(cfg.basedir),".session/")
      method.insert = cfg.watch,    private|const|string, (cat,"/media-rocinante/Downloads/rtorrent-flood/","watch/")
      fs.mkdir.recursive = (cat,(cfg.basedir))
      fs.mkdir = (cat,(cfg.download))
      fs.mkdir = (cat,(cfg.logs))
      fs.mkdir = (cat,(cfg.session))
      fs.mkdir = (cat,(cfg.watch))
      fs.mkdir = (cat,(cfg.watch),"/load")
      fs.mkdir = (cat,(cfg.watch),"/start")
      schedule2 = watch_load, 11, 10, ((load.verbose, (cat, (cfg.watch), "load/*.torrent")))
      schedule2 = watch_start, 10, 10, ((load.start_verbose, (cat, (cfg.watch), "start/*.torrent")))
      dht.add_bootstrap = dht.transmissionbt.com:6881
      dht.add_bootstrap = dht.libtorrent.org:25401
      throttle.max_uploads.set = 100
      throttle.max_uploads.global.set = 250
      throttle.min_peers.normal.set = 20
      throttle.max_peers.normal.set = 60
      throttle.min_peers.seed.set = 30
      throttle.max_peers.seed.set = 80
      trackers.numwant.set = 80
      network.port_range.set = 6881-6881
      network.port_random.set = no
      network.max_open_files.set = 600
      network.max_open_sockets.set = 300
      pieces.memory.max.set = 1800M
      session.path.set = (cat, (cfg.session))
      directory.default.set = (cat, (cfg.download))
      log.execute = (cat, (cfg.logs), "execute.log")
      encoding.add = utf8
      system.daemon.set = true
      system.umask.set = 0002
      system.cwd.set = (directory.default)
      network.http.max_open.set = 50
      network.http.dns_cache_timeout.set = 25
      network.scgi.open_local = (cat,(cfg.basedir),rtorrent.sock)
      print = (cat, "Logging to ", (cfg.logfile))
      log.open_file = "log", (cfg.logfile)
      log.add_output = "info", "log"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: bittorrent
        type: LoadBalancer
        externalIPs:
        - 192.168.69.216
        port:
          port: 50483
          name: bittorrent
          protocol: TCP
          targetPort: 6881
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: flood.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "flood.devbu.io"
    persistence:
      config:
        enabled: true
        existingClaim: rtorrent-flood-config-v1
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      supplementalGroups:
      - 100
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    podAnnotations:
      configmap.reloader.stakater.com/reload: "rtorrent-flood-config"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 4000Mi
