---
version: "3"

services:
  minio:
    image: minio/minio:RELEASE.2021-05-18T00-53-28Z
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: ""
      MINIO_SECRET_KEY: ""
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_UPDATE: "off"
    command: server /data
    ports:
    - "9000:9000"
    volumes:
    - "minio-data:/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.rule=Host(`minio.devbu.io`)"
    - "traefik.http.routers.minio.entrypoints=websecure"
    - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
volumes:
  minio-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/share/Data/ContainerStation/minio"
