---

version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2021-02-24T18-44-45Z
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: ""
      MINIO_SECRET_KEY: ""
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_UPDATE: "off"
    command: server /data
    ports:
    - 9000:9000
    volumes:
    - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/minio'
