---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-charts.banzaicloud.com
      chart: thanos
      version: 0.3.31
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-charts
        namespace: flux-system
      interval: 5m
  values:
    query:
      replicaCount: 3
      replicaLabels:
      - replica
      http:
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "internal"
          hosts:
          - thanos.devbu.io
          tls:
          - hosts:
            - thanos.devbu.io
    compact:
      retentionResolution1h: 5y
    objstore:
      type: S3
      config:
        region: ""
        insecure: false
        signature_version2: false
        put_user_metadata: {}
        http_config:
          idle_conn_timeout: 0s
          response_header_timeout: 0s
          insecure_skip_verify: false
        trace:
          enable: false
        part_size: 0
  valuesFrom:
  - kind: Secret
    name: "thanos-helm-values"
