---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: forecastle
      version: v1.0.61
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 5m
  values:
    forecastle:
      config:
        title: "Devin's Apps"
        namespaceSelector:
          matchNames:
          - media
          - home
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
        - host: forecastle.devbu.io
          paths:
          - /
        tls:
        - hosts:
          - forecastle.devbu.io
