---

# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration

# Don't define the host as control plane nodes
k3s_control_node: false

# k3s settings for all worker nodes
k3s_agent:
  node-external-ip: "{{ ansible_host }}"
  node-ip: "{{ digitalocean_private_ip }}"
  # # Apply Labels
  # node-label:
  # - "node-role.kubernetes.io/worker=true"
