---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: drone/drone
      tag: 1.10.1
    updateStrategy:
      type: Recreate
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: "drone.${SECRET_CLUSTER_DOMAIN}"
        paths:
        - "/"
      tls:
      - hosts:
        - "drone.${SECRET_CLUSTER_DOMAIN}"
    env:
      DRONE_SERVER_HOST: "drone.${SECRET_CLUSTER_DOMAIN}"
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_GITEA_SERVER: "https://gitea.${SECRET_CLUSTER_DOMAIN}"
      DRONE_SERVER_PROTO: https
      DRONE_PROMETHEUS_ANONYMOUS_ACCESS: true
      DRONE_USER_CREATE: "username:devin,admin:true"
      DRONE_LOGS_TEXT: true
      DRONE_LOGS_PRETTY: true
      DRONE_LOGS_COLOR: true
      DRONE_RPC_SECRET: "${SECRET_DRONE_RPC_SECRET}"
      DRONE_GITEA_CLIENT_ID: "${SECRET_DRONE_GITEA_CLIENT_ID}"
      DRONE_GITEA_CLIENT_SECRET: "${SECRET_DRONE_GITEA_CLIENT_SECRET}"
    rbac:
      buildNamespaces:
      - home
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
    persistentVolume:
      enabled: true
      storageClass: "rook-ceph-block"
