---

# Below vars are for the xanmanning.k3s role
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

# Define the host as a control plane node
k3s_control_node: true

# k3s settings for control-plane nodes node
k3s_server:
  node-external-ip: "{{ ansible_host }}"
  node-ip: "{{ digitalocean_private_ip }}"
  tls-san:
  - "{{ k3s_control_node_address }}"
  docker: false
  flannel-backend: 'none' # This needs to be in quotes
  disable:
  - flannel
  - traefik
  - servicelb
  - metrics-server
  - local-storage
  disable-network-policy: true
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "172.20.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "172.25.0.0/16"
  # # Apply taints
  # node-taint:
  # - "node-role.kubernetes.io/master=true:NoSchedule"
