---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-frigate-rocinante-pv
spec:
  storageClassName: frigate-rocinante
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.42.40
    path: /Media/Videos/frigate
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-frigate-rocinante-pvc
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: frigate-rocinante
  resources:
    requests:
      storage: 1Mi
