---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-cleanup-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.lwolf.org
      chart: kube-cleanup-operator
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: lwolf-charts
        namespace: flux-system
      interval: 5m
  values:
    args:
    - --delete-failed-after=60m
