---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovatebot.helm.repository: https://weaveworks.github.io/kured
      chart: kured
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: weaveworks/kured
      tag: 1.5.0
    configuration:
      startTime: "2:00"
      endTime: "6:00"
    service:
      create: true
    metrics:
      create: true
