---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovatebot.helm.repository: https://charts.bitnami.com/bitnami
      chart: metrics-server
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/metrics-server
      tag: 0.4.1
    extraArgs:
      kubelet-insecure-tls: true
      kubelet-preferred-address-types: InternalIP,ExternalIP,Hostname
