---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      tag: v0.4.0
    args:
      - --kubelet-insecure-tls=true
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
