---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.23.2.4656-85f0adf5b
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
      - 44
      - 109
      - 100
    service:
      enabled: true
      type: LoadBalancer
      externalIPs:
      - "${SVC_PLEX_ADDRESS}"
      externalTrafficPolicy: Local
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - host: "plex.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "plex.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      tmp:
        enabled: true
        emptyDir:
          enabled: true
          medium: "Memory"
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
      readOnly: true
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k8s-worker-d
              - k8s-worker-e
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 24000Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-promtail"
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.2.1
        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
        - name: promtail/plex
          path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
        - name: promtail/plex/plugins
          path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        securityContext:
          runAsUser: 0
