---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/zwave-js/zwavejs2mqtt
      tag: 4.4.0
    env:
      TZ: "America/New_York"
    service:
      additionalPorts:
      - name: websocket
        port: 3000
    securityContext:
      privileged: true
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
      - host: "zwavejs2mqtt.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "zwavejs2mqtt.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: zwavejs2mqtt-config-v1
        mountPath: "/usr/src/app/store"
    additionalVolumeMounts:
    - name: usb
      mountPath: /dev/serial/by-id/usb-0658_0200-if00
    additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/serial/by-id/usb-0658_0200-if00
        type: CharDevice
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/custom-zwave
              operator: In
              values:
              - "true"
