---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_LB_BLOCKY: "192.168.69.115"
  CLUSTER_LB_COREDNS: "192.168.69.180"
  CLUSTER_LB_HOME_ASSISTANT: "192.168.69.105"
  CLUSTER_LB_INGRESS_EXTERNAL: "192.168.69.100"
  CLUSTER_LB_INGRESS_INTERNAL: "192.168.69.101"
  CLUSTER_LB_JELLYFIN: "192.168.69.220"
  CLUSTER_LB_LOKI: "192.168.69.155"
  CLUSTER_LB_PLEX: "192.168.69.140"
  CLUSTER_LB_QBITTORRENT: "192.168.69.130"
  CLUSTER_LB_RTORRENT_FLOOD: "192.168.69.216"
  CLUSTER_LB_VERNEMQ: "192.168.69.110"
