---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 9.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.4.1
    env:
      TZ: "America/New_York"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: bittorrent
        type: LoadBalancer
        externalIPs:
        - 192.168.69.130
        port:
          port: 50413
          name: bittorrent
          protocol: TCP
          targetPort: 6881
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
        # Custom themes provided by https://github.com/gilbN/theme.park
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_hide_header "x-webkit-csp";
          proxy_hide_header "content-security-policy";
          proxy_hide_header "X-Frame-Options";
          proxy_set_header Accept-Encoding "";
          sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/qbittorrent/organizr-dark.css"></head>';
          sub_filter_once on;
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://user-images.githubusercontent.com/33867119/33150262-ba172c24-cfe3-11e7-8bc0-09ac1735844c.png"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
      - host: qb.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "qb.devbu.io"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
    podSecurityContext:
      supplementalGroups:
      - 100
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
    - name: media-serenity
      mountPath: "/media-serenity"
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    - name: media-serenity
      persistentVolumeClaim:
        claimName: nfs-media-serenity-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: "qbittorrent-promtail"
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.2.1
        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
        - name: promtail/qbittorrent
          path: /config/data/qBittorrent/logs/*.log
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        securityContext:
          runAsUser: 0
