---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.4.1
    env:
      TZ: "America/New_York"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: bittorrent
        type: LoadBalancer
        loadBalancerIP: "${LB_QBITTORRENT_IP}"
        port:
          port: 50413
          name: bittorrent
          protocol: TCP
          targetPort: 6881
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - host: "qb.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "qb.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
    podSecurityContext:
      supplementalGroups:
      - 100
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
    - name: media-serenity
      mountPath: "/media-serenity"
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    - name: media-serenity
      persistentVolumeClaim:
        claimName: nfs-media-serenity-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: "qbittorrent-promtail"
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.2.1
        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
        - name: promtail/qbittorrent
          path: /config/data/qBittorrent/logs/*.log
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        securityContext:
          runAsUser: 0
