---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gonic
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: gonic
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    # initContainers:
    # - name: make-cache-dir
    #   image: busybox
    #   command: ["sh", "-c", "mkdir -p /data/cache"]
    #   volumeMounts:
    #   - name: config
    #     mountPath: /data
    image:
      repository: sentriz/gonic
      tag: v0.13.1
    env:
      TZ: "America/New_York"
      GONIC_MUSIC_PATH: "/media-serenity/Library/Music"
      GONIC_PODCAST_PATH: "/media-serenity/Library/Podcasts"
      GONIC_CACHE_PATH: "/data/cache"
      GONIC_SCAN_INTERVAL: "120"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - host: "music.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "music.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: gonic-config-v1
        mountPath: "/data"
    podSecurityContext:
      supplementalGroups:
      - 100
    additionalVolumeMounts:
    - name: media-serenity
      mountPath: "/media-serenity"
      readOnly: true
    additionalVolumes:
    - name: media-serenity
      persistentVolumeClaim:
        claimName: nfs-media-serenity-pvc
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1500Mi
