---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: stash
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: stashapp/stash
      tag: latest@sha256:e2fc99d15b55699e91d45f5ee341513a48bd6dd633dd358b18ef4bc485695a94
    env:
      TZ: "America/New_York"
      STASH_PORT: "9999"
      STASH_STASH: "/media-rocinante"
      STASH_GENERATED: "/root/.stash/generated"
      STASH_METADATA: "/root/.stash/metadata"
      STASH_CACHE: "/root/.stash/cache"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: stash.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "stash.devbu.io"
    persistence:
      config:
        enabled: true
        existingClaim: stash-config-v1
        mountPath: /root/.stash
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
      readOnly: true
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 2000Mi
