---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdaemon
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: appdaemon
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8sathome/appdaemon
      tag: v4.0.5
      pullPolicy: Always
    env:
      TZ: "America/New_York"
      DASH_URL: "http://0.0.0.0:5050"
      HA_URL: "http://home-assistant:8123"
    service:
      port:
        port: 5050
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: appdaemon.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - appdaemon.devbu.io
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "1Gi"
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.8.0
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "internal"
          hosts:
          - host: appdaemon-config.devbu.io
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - appdaemon-config.devbu.io
        volumeMounts:
        - name: config
          mountPath: /config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 2000m
  valuesFrom:
  - kind: Secret
    name: "appdaemon-helm-values"
