---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-media-server-test
  namespace: testing
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex-media-server
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/plex-media-server
      tag: v1.22.0.4163-d8c4875dd
      pullPolicy: Always
    env:
      TZ: "America/New_York"
      ADVERTISE_IP: "http://192.168.69.200:32400"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
      - 44
      - 109
    service:
      enabled: true
      type: LoadBalancer
      externalIPs:
      - 192.168.69.200
      externalTrafficPolicy: Local
      port:
        port: 32400
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: plex-media-server-test.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "plex-media-server-test.devbu.io"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "10Gi"
      transcode:
        enabled: false
        emptyDir:
          medium: "Memory"
    additionalVolumeMounts:
    - name: testing-rocinante
      mountPath: "/media-rocinante"
      readOnly: true
    additionalVolumes:
    - name: testing-rocinante
      persistentVolumeClaim:
        claimName: nfs-testing-rocinante-pvc
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 2000m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 6000Mi
