---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.3.1
    env:
      TZ: "America/New_York"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-basic-auth@kubernetescrd"
      hosts:
      - host: "sabnzbd.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "sabnzbd.${SECRET_DOMAIN}"
      additionalIngresses:
      - enabled: true
        nameSuffix: "api"
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "sabnzbd.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "sabnzbd.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-v1
    podSecurityContext:
      supplementalGroups:
      - 100
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 7500Mi
