---

all:
  children:
    # Control Plane group, do not change the 'control-plane' name
    # hosts should match the filenames in 'host_vars'
    master-nodes:
      hosts:
        k8s-master-a:
        k8s-master-b:
        k8s-master-c:
    # Node group, do not change the 'node' name
    # hosts should match the filenames in 'host_vars'
    worker-nodes:
      hosts:
        k8s-worker-a:
        k8s-worker-b:
        k8s-worker-c:
        k8s-worker-d:
        k8s-worker-e:
    # Storage group, these are my NAS devices
    # hosts should match the filenames in 'host_vars'
    storage:
      hosts:
        nas-rocinante:
        nas-serenity:
