---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-disaster-recovery-policy
  namespace: kasten-io
spec:
  frequency: "@hourly"
  retention:
    hourly: 24
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  selector:
  matchExpressions:
  - key: k10.kasten.io/appNamespace
    operator: In
    values:
    - kasten-io
  actions:
  - action: backup
    backupParameters:
      filters: {}
      profile:
        name: minio
        namespace: kasten-io
