---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: b4bz/homer
      tag: 20.11.28
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    additionalContainers:
    - name: vscode
      image: codercom/code-server:3.7.2
      imagePullPolicy: IfNotPresent
      workingDir: /www/assets
      args:
      - "--port"
      - "12431"
      - "--auth"
      - "none"
      ports:
      - name: vscode
        containerPort: 12431
        protocol: TCP
      volumeMounts:
      - name: config
        mountPath: /www/assets
      securityContext:
        runAsUser: 0
    service:
      port:
        port: 8080
      additionalServices:
      - enabled: true
        nameSuffix: vscode
        type: ClusterIP
        port:
          port: 12431
          name: vscode
          protocol: TCP
          targetPort: 12431
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: start.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - start.devbu.io
      additionalIngresses:
      - enabled: true
        nameSuffix: "vscode"
        serviceName: homer-vscode
        servicePort: 12431
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
        - host: start-editor.devbu.io
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - start-editor.devbu.io
    # additionalVolumes: []
    # additionalVolumeMounts: []
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "1Gi"
    # podSecurityContext:
    #   runAsUser: 0
    #   fsGroup: 0
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 2000m
