---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: b4bz/homer
      tag: 20.12.07
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    service:
      port:
        port: 8080
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: start.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - start.devbu.io
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "1Gi"
    addons:
      codeserver:
        enabled: true
        workingDir: "/www/assets"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "internal"
          hosts:
          - host: start-config.devbu.io
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - start-config.devbu.io
        volumeMounts:
        - name: config
          mountPath: /www/assets
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 2000m
