---

version: '3.7'
services:
  nexus:
    image: sonatype/nexus3:3.31.0
    restart: unless-stopped
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    ports:
    - 8081:8081
    - 8082:8082
    - 5000:5000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - nexus-data:/nexus-data
    labels:
    - traefik.enable=true
    - traefik.http.routers.nexus.rule=Host(`nexus.devbu.io`)
    - traefik.http.routers.nexus.service=nexus
    - traefik.http.routers.nexus.entrypoints=websecure
    - traefik.http.routers.nexus.tls.certresolver=letsencrypt
    - traefik.http.services.nexus.loadbalancer.server.port=8081
    - traefik.http.routers.registry.service=registry
    - traefik.http.routers.registry.rule=Host(`registry.devbu.io`)
    - traefik.http.routers.registry.entrypoints=websecure
    - traefik.http.routers.registry.tls.certresolver=letsencrypt
    - traefik.http.services.registry.loadbalancer.server.port=5000
    - traefik.http.routers.cache.service=cache
    - traefik.http.routers.cache.rule=Host(`registry-cache.devbu.io`)
    - traefik.http.routers.cache.entrypoints=websecure
    - traefik.http.routers.cache.tls.certresolver=letsencrypt
    - traefik.http.services.cache.loadbalancer.server.port=8082
volumes:
  nexus-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/nexus'
