---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ombi
      version: 6.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: k8sathome/ombi
      tag: v4.0.932
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - host: ombi.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "ombi.devbu.io"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "1Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
