---

version: '3.7'
services:
  scrutiny:
    container_name: scrutiny
    image: analogj/scrutiny:v0.3.7-collector
    cap_add:
    - SYS_RAWIO
    environment:
      SCRUTINY_API_ENDPOINT: "https://scrutiny.devbu.io"
    volumes:
    - /lib/udev:/run/udev:ro
    - scrutiny-data:/scrutiny/config
    devices:
    - "/dev/sda"
    - "/dev/sdb"
    - "/dev/sdc"
    - "/dev/sdd"
    - "/dev/sde"
    - "/dev/sdf"
    - "/dev/sdg"
    - "/dev/sdh"
volumes:
  scrutiny-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/scrutiny'
