---
version: "3"

services:
  scrutiny:
    image: analogj/scrutiny:v0.3.12-collector
    environment:
      SCRUTINY_API_ENDPOINT: "https://scrutiny.devbu.io"
    cap_add:
    - SYS_RAWIO
    volumes:
    - "/lib/udev:/run/udev:ro"
    - "scrutiny-data:/scrutiny/config"
    devices:
    - "/dev/sda"
    - "/dev/sdb"
    - "/dev/sdc"
    - "/dev/sdd"
    - "/dev/sde"
    - "/dev/sdf"
    - "/dev/sdg"
    - "/dev/sdh"
volumes:
  scrutiny-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/share/Data/ContainerStation/scrutiny"
