---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: jesec/flood
      tag: 4.5.0
    env:
      FLOOD_OPTION_RUNDIR: /data
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_QBURL: "http://qbittorrent.media.svc.cluster.local:8080"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: flood.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "flood.devbu.io"
    persistence:
      config:
        enabled: true
        existingClaim: flood-config-v1
        mountPath: /data
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1000Mi
  valuesFrom:
  - kind: Secret
    name: "flood-helm-values"
