---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: k10
      version: 3.0.12
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: Devbu
      email: devin.kray@gmail.com
    global:
      persistence:
        storageClass: rook-ceph-block
    auth:
      tokenAuth:
        enabled: true
    prometheus:
      enabled: true
      server:
        persistentVolume:
          enabled: false
    clusterName: k8s
    ingress:
      create: true
      class: "internal"
      host: k10.devbu.io
      annotations:
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/app-root: /k10
      urlPath: k10
      hosts:
      - k10.devbu.io
      tls:
        enabled: true
        secretName: devbu-io-tls
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          kind: Ingress
          name: k10-ingress
        patch:
        - op: replace
          path: /spec/rules/0/http/paths/0/path
          value: /
