---

name: pulumi

on:
  workflow_dispatch:
  push:
    branches:
    - main
    # paths:
    # - "ansible/**"

# defaults:
#   run:
#     working-directory: ./ansible/tests

jobs:
  test-ubuntu-prepare:

    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Upgrade pip and display Python and PIP versions
      run: |
        sudo apt-get update
        sudo apt-get install -y python*-wheel python*-yaml
        python -m pip install --upgrade pip
        python -V
        pip --version

    - name: Install Ansible
      run: |
        python3 -m pip install --user --force-reinstall --upgrade 'ansible>=2.10.0'
        ansible --version

    # - name: Install Ansible
    #   run: |
    #     sudo apt update
    #     sudo apt install software-properties-common
    #     sudo apt-add-repository --yes --update ppa:ansible/ansible
    #     sudo apt install ansible
    #     ansible --version

    # - name: Install Pulumi
    #   run: |
    #     curl -fsSL https://get.pulumi.com | sh
    #     sudo mv /home/runner/.pulumi/bin/pulumi /usr/local/bin
    #     pulumi version

    # - name: Install deps
    #   run: |
    #     curl -sL -o yq "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    #     sudo mv yq /usr/local/bin
    #     chmod +x /usr/local/bin/yq
    #     yq --version

    # - name: Create cloud resources
    #   uses: pulumi/actions@v1
    #   with:
    #     command: up
    #   env:
    #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    #     PULUMI_ROOT: ./ansible/tests
    #     PULUMI_STACK_NAME: "ubuntu-2010"

    # - name: Get Ansible inventory
    #   uses: pulumi/actions@v1
    #   with:
    #     command: stack output --json
    #   env:
    #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    #     PULUMI_ROOT: ./ansible/tests
    #     PULUMI_STACK_NAME: ubuntu-2010

    # - name: Destroy cloud resources
    #   uses: pulumi/actions@v1
    #   with:
    #     command: destroy
    #   env:
    #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    #     PULUMI_ROOT: ./ansible/tests
    #     PULUMI_STACK_NAME: ubuntu-2010

    # - name: Run Tests
    #   working-directory: ./ansible/tests
    #   env:
    #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    #   run: |
    #     bash run-test.sh

    # - name: Clean up
    #   working-directory: ./ansible/tests
    #   env:
    #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    #   run: |
    #     pulumi destroy --yes
