---

name: Test Ansible Roles

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/ansible-tests.yaml'
  pull_request:
    paths:
    - 'server/ansible/**'

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create local PATH
      run: |
        mkdir -p "${HOME}/.local/bin"
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"

    - name: Install yq
      run: |
        curl -sLO "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
        mv yq_linux_amd64 "${HOME}/.local/bin/yq"
        chmod +x "${HOME}/.local/bin/yq"
        yq --version

    - name: Install Pulumi
      run: |
        curl -fsSL https://get.pulumi.com | sh
        mv /home/runner/.pulumi/bin/pulumi "${HOME}/.local/bin/pulumi"
        chmod +x "${HOME}/.local/bin/pulumi"
        pulumi version

    - name: Cache node modules
      id: node_modules_cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./server/ansible/tests/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install npm deps
      working-directory: ./server/ansible/tests
      run: npm install
      if: steps.node_modules_cache.outputs.cache-hit != 'true'

    - name: Change Pulumi stack
      working-directory: ./server/ansible/tests
      run: pulumi stack select single-control-plane

    - name: Create cloud resources
      working-directory: ./server/ansible/tests
      run: pulumi up --yes

    - name: Save Ansible inventory
      working-directory: ./server/ansible/tests
      run: pulumi stack output --json | yq eval -P - > /tmp/hosts.yml

    # - name: Save Ansible inventory
    #   working-directory: ./server/ansible/tests
    #   run: pulumi stack output --json | python3 -c 'import sys, yaml, json; print(yaml.dump(json.loads(sys.stdin.read()),sort_keys=False))'


    - name: Upload Ansible inventory
      uses: actions/upload-artifact@v2
      with:
        name: hosts
        path: /tmp/hosts.yml

  install:
    needs:
    - setup
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create local PATH
      run: |
        mkdir -p "${HOME}/.local/bin"
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip and display Python and PIP versions
      run: |
        sudo apt-get update
        sudo apt-get install -y python*-wheel python*-yaml
        python3 -m pip install --no-cache-dir --upgrade pip
        python3 -V
        pip --version

    - name: Upgrade Ansible
      run: |
        python3 -m pip install --no-cache-dir --force-reinstall --upgrade 'ansible>=3.0.0'
        ansible --version

    - name: Install Ansible Galaxy roles
      working-directory: ./server/ansible
      run: ansible-galaxy install -r requirements.yml

    - name: Download Ansible inventory
      uses: actions/download-artifact@v2
      with:
        name: hosts
        path: ./server/ansible/inventory/e2e/

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

    - name: Wait for all hosts to become ready
      run: |
        attempt_counter=0
        max_attempts=10
        until $(ansible all -i ./server/ansible/inventory/e2e/hosts.yml --one-line -m ping >/dev/null 2>&1); do
            if [ ${attempt_counter} -eq ${max_attempts} ];then
              echo "Max attempts reached"
              exit 1
            fi
            printf '.'
            attempt_counter=$(($attempt_counter+1))
            sleep 5
        done

    # - name: Run ubuntu/upgrade playbook
    #   working-directory: ./server/ansible
    #   run: ansible-playbook -i ./inventory/e2e/hosts.yml ./playbooks/ubuntu/upgrade.yml

    - name: Run ubuntu/prepare playbook
      working-directory: ./server/ansible
      run: ansible-playbook -i ./inventory/e2e/hosts.yml ./playbooks/ubuntu/prepare.yml

    - name: Reboot all nodes
      working-directory: ./server/ansible
      run: ansible all -i ./inventory/e2e/hosts.yml --one-line -m reboot

    - name: Run k3s/install playbook
      working-directory: ./server/ansible
      run: ansible-playbook -i ./inventory/e2e/hosts.yml ./playbooks/k3s/install.yml

    - name: Upload kubeconfig
      uses: actions/upload-artifact@v2
      with:
        name: kubeconfig
        path: /tmp/kubeconfig

  verify:
    needs:
    - setup
    - install
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create local PATH
      run: |
        mkdir -p "${HOME}/.local/bin"
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"

    # - name: Install yq
    #   run: |
    #     curl -sLO "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    #     mv yq_linux_amd64 "${HOME}/.local/bin/yq"
    #     chmod +x "${HOME}/.local/bin/yq"
    #     yq --version

    - name: Install kubectl
      run: |
        curl -sLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo mv kubectl "${HOME}/.local/bin/kubectl"
        chmod +x "${HOME}/.local/bin/kubectl"
        kubectl version --client

    - name: Download Ansible inventory
      uses: actions/download-artifact@v2
      with:
        name: hosts
        path: ./server/ansible/inventory/e2e/

    - name: Download kubeconfig
      uses: actions/download-artifact@v2
      with:
        name: kubeconfig
        path: ./server/ansible/

    # - name: Get HTTP Load Balancer IP
    #   id: ip
    #   run: |
    #     LOAD_BALANCER_IP=$(yq e '.all | .. | select(.digitalocean_http_ip) | .digitalocean_http_ip' ./server/ansible/inventory/e2e/hosts.yml | head -n 1)
    #     echo ::set-output name=ip::${LOAD_BALANCER_IP}

    - name: Get HTTP Load Balancer IP
      id: ip
      run: |
        LOAD_BALANCER_IP=$(grep -Po 'digitalocean_http_ip: \K[^\n]*' ./server/ansible/inventory/e2e/hosts.yml | head -n 1)
        echo ::set-output name=ip::${LOAD_BALANCER_IP}

    # - name: Wait for nodes to become ready
    #   run: |
    #     nodes=$(yq eval '.all.children.**.* | keys | .[]' ./server/ansible/inventory/e2e/hosts.yml)
    #     for node in $nodes; do
    #         kubectl --kubeconfig ./server/ansible/kubeconfig wait "nodes/${node}" --for=condition=ready --timeout=2m
    #     done

    - name: Wait for nodes to become ready
      run: |
        nodes=$(grep -Po 'k8s-[a-z-_]+' ./server/ansible/inventory/e2e/hosts.yml)
        for node in $nodes; do
            kubectl --kubeconfig ./server/ansible/kubeconfig wait "nodes/${node}" --for=condition=ready --timeout=2m
        done

    - name: Wait for coredns deployment to rollout
      run: kubectl --kubeconfig ./server/ansible/kubeconfig -n kube-system wait deployment.apps/coredns --for=condition=available --timeout=1m

    - name: Wait for calico deployment to rollout
      run: kubectl --kubeconfig ./server/ansible/kubeconfig -n tigera-operator wait deployment.apps/tigera-operator --for=condition=available --timeout=1m

    - name: Create nginx service and deployment
      run: kubectl --kubeconfig ./server/ansible/kubeconfig apply -f ./server/ansible/tests/nginx-deployment.yaml

    - name: Wait for nginx deployment to rollout
      run: kubectl --kubeconfig ./server/ansible/kubeconfig -n default wait deployment.apps/nginx --for=condition=available --timeout=2m

    - name: Wait for 200 HTTP status from nginx deployment
      run: |
        attempt_counter=0
        max_attempts=10
        until [[ $(curl --head --silent --max-time 5 --output /dev/null -w %{http_code} http://${{ steps.ip.outputs.ip }}:80) =~ 2[0-9][0-9]  ]]; do
            if [ ${attempt_counter} -eq ${max_attempts} ];then
              echo "Max attempts reached"
              exit 1
            fi
            printf '.'
            attempt_counter=$(($attempt_counter+1))
            sleep 5
        done

    - name: Debug failure
      if: failure()
      run: |
        kubectl --kubeconfig ./server/ansible/kubeconfig get nodes -o wide
        kubectl --kubeconfig ./server/ansible/kubeconfig -n default get all
        kubectl --kubeconfig ./server/ansible/kubeconfig -n tigera-operator get all
        kubectl --kubeconfig ./server/ansible/kubeconfig -n calico-system get all
        kubectl --kubeconfig ./server/ansible/kubeconfig -n kube-system get all

  teardown:
    needs:
    - setup
    - install
    - verify
    if: always()
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create local PATH
      run: |
        mkdir -p "${HOME}/.local/bin"
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"

    - name: Install Pulumi
      run: |
        curl -fsSL https://get.pulumi.com | sh
        mv /home/runner/.pulumi/bin/pulumi "${HOME}/.local/bin/pulumi"
        chmod +x "${HOME}/.local/bin/pulumi"
        pulumi version

    - name: Cache node modules
      id: node_modules_cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: "./server/ansible/tests/node_modules"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install npm deps
      working-directory: "./server/ansible/tests"
      run: npm install
      if: steps.node_modules_cache.outputs.cache-hit != 'true'

    - name: Change Pulumi stack
      working-directory: "./server/ansible/tests"
      run: pulumi stack select single-control-plane

    - name: Destroy cloud resources
      working-directory: "./server/ansible/tests"
      run: pulumi destroy --yes
