---

name: Lint

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: yamllint
      uses: reviewdog/action-yamllint@v1
      with:
        yamllint_flags: "-c .github/yamllint.config.yaml ./cluster"
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        path: "./hack"
        level: "error"
  markdownlint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: markdownlint
      uses: reviewdog/action-markdownlint@v0.1
