---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 3.1.4
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "rook-ceph-block"
    ingress:
      enabled: true
      # ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
      - "gitea.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "gitea.${SECRET_DOMAIN}"
    service:
      http:
        port: 3000
    gitea:
      admin:
        username: "devin"
        email: "${SECRET_EMAIL}"
        password: "${SECRET_GITEA_ADMIN_PASSWORD}"
      security:
        SECRET_KEY: "${SECRET_GITEA_SECRET_KEY}"
      config:
        APP_NAME: "Home Gitea"
        server:
          ROOT_URL: "https://gitea.${SECRET_DOMAIN}"
          DISABLE_SSH: true
          PPROF_ENABLED: true
        respository:
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
        database:
          DB_TYPE: postgres
          HOST: 192.168.42.40:5432
          NAME: gitea
          USER: admin
          PASSWD: "${SECRET_GITEA_POSTRES_PASSWORD}"
      database:
        builtIn:
          postgresql:
            enabled: false
      cache:
        builtIn:
          enabled: true
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          kind: Ingress
          name: gitea
        patch:
        - op: add
          path: /spec/ingressClassName
          value: traefik
